name: Sentry Release
description: Wrapper for getsentry/action-release

inputs:
  sentry_auth_token:
    description: |-
      Authentication token for Sentry.
      SENTRY_AUTH_TOKEN environment variable.
    required: true
  sentry_org:
    description: |-
      The organization slug in Sentry.
      SENTRY_ORG environment variable.
    required: true
  sentry_project:
    description: |-
      The project slug in Sentry.
      SENTRY_PROJECT environment variable.
    required: true
  sentry_url:
    description: |-
      The Sentry server URL.
      SENTRY_URL environment variable.
    required: false
    default: "https://sentry.io"
  environment:
    description: |-
      Set the environment for this release. E.g. "production" or "staging".
      Omit to skip adding deploy to release.
    required: false
  sourcemaps:
    description: |-
      Space-separated list of paths to JavaScript source maps.
      Omit to skip uploading sourcemaps.
    required: false
  inject:
    description: |-
      Injects Debug IDs into source files and source maps to ensure proper
      un-minifcation of your stacktraces.
      Does nothing if "sourcemaps" was not set.
    default: 'true'
    required: false
  dist:
    description: |-
      Unique identifier for the distribution, used to further segment your
      release.
      Usually your build number.
    required: false
  finalize:
    description: |-
      When false, omit marking the release as finalized and released.
    default: 'true'
  ignore_missing:
    description: |-
      When the flag is set and the previous release commit was not found in
      the repository, will create a release with the default commits count
      instead of failing the command.
    default: 'false'
    required: false
  ignore_empty:
    description: |-
      When the flag is set, command will not fail and just exit silently if no
      new commits for a given release have been found.
    default: 'false'
    required: false
  started_at:
    description: |-
      Unix timestamp of the release start date. Omit for current time.
    required: false
  release:
    description: |-
      Identifier that uniquely identifies the release.
      Should match the "release" property in your Sentry SDK init call if one
      was set.
      Omit to auto-generate one.
    required: false
  release_prefix:
    description: |-
      Value prepended to auto-generated release version.
    required: false
  set_commits:
    description: |-
      Specify whether to set commits for the release.
      When "manual", you need to provide the repository, commit, and previous commit.
      One of: "auto", "skip", "manual"
    required: false
  repo:
    description: |-
      The repository to set commits for in "repo-owner/repo-name" format.
      Only used when "set_commits" is "manual".
    required: false
  commit:
    description: |-
      The commit SHA of the current release you are creating.
      Only used when "set_commits" is "manual".
    required: false
  previous_commit:
    description: |-
      The commit SHA of the previous release.
      Required when "set_commits" is "manual".
    required: false
  projects:
    description: |-
      Space-separated list of projects.
      Defaults to the env variable "SENTRY_PROJECT" if not provided.
    required: false
  url_prefix:
    description: |-
      Adds a prefix to source map urls after stripping them.
    required: false
  strip_common_prefix:
    description: |-
      Will remove a common prefix from uploaded filenames. Useful for removing
      a path that is build-machine-specific.
      Note: Will not remove common prefixes across two or more directories
      provided to "sourcemap". E.g. Setting
      "sourcemap": "./dist/js ./dist/asset/js" will strip "./dist" for the first
      directory and "./dist/assets/js" for the
    default: 'false'
    required: false
  working_directory:
    description: |-
      Directory to collect sentry release information from.
      Useful when collecting information from a non-standard checkout directory.
    required: false
  disable_telemetry:
    description: |-
      The action sends telemetry data and crash reports to Sentry. This helps
      us improve the action.
      You can turn this off by setting this flag.
    default: 'false'
    required: false
  disable_safe_directory:
    description: |-
      The action needs access to the repo it runs in. For that we need to
      configure git to mark the repo directory a safe directory.
      You can turn this off by setting this flag.
    default: 'false'
    required: false

runs:
  using: composite
  steps:
  - uses: getsentry/action-release@dab6548b3c03c4717878099e43782cf5be654289 # v3.5.0
    env:
      SENTRY_AUTH_TOKEN: ${{ inputs.sentry_auth_token }}
      SENTRY_ORG: ${{ inputs.sentry_org }}
      SENTRY_PROJECT: ${{ inputs.sentry_project }}
      SENTRY_URL: ${{ inputs.sentry_url }}
    with:
      environment: ${{ inputs.environment }}
      sourcemaps: ${{ inputs.sourcemaps }}
      inject: ${{ inputs.inject }}
      dist: ${{ inputs.dist }}
      finalize: ${{ inputs.finalize }}
      ignore_missing: ${{ inputs.ignore_missing }}
      ignore_empty: ${{ inputs.ignore_empty }}
      started_at: ${{ inputs.started_at }}
      release: ${{ inputs.release }}
      release_prefix: ${{ inputs.release_prefix }}
      set_commits: ${{ inputs.set_commits }}
      repo: ${{ inputs.repo }}
      commit: ${{ inputs.commit }}
      previous_commit: ${{ inputs.previous_commit }}
      projects: ${{ inputs.projects }}
      url_prefix: ${{ inputs.url_prefix }}
      strip_common_prefix: ${{ inputs.strip_common_prefix }}
      working_directory: ${{ inputs.working_directory }}
      disable_telemetry: ${{ inputs.disable_telemetry }}
      disable_safe_directory: ${{ inputs.disable_safe_directory }}
