name: Publish to Buf
description: Wrapper for publishing protos to buf.build

inputs:
  buf_token:
    description: buf.build api token
    required: true
  buf_user:
    description: buf.build api user
    required: true
  path:
    description: path to protos
    required: true

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0

  - name: Buf Setup
    uses: bufbuild/buf-setup-action@v1

  - name: Publish Protobufs to Buf
    uses: bufbuild/buf-push-action@v1
    with:
      # TODO: Reuse GH tag on buf when buf-push-action supports specifying
      # it: https://github.com/bufbuild/buf-push-action/issues/20
      input: ${{ inputs.path }}
      buf_token: ${{ inputs.buf_token }}
