name: Check Rust Licenses
description: Check Rust licenses and source bans

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: 'false'
  - name: Check license and source bans - advisories
    continue-on-error: true
    uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
    with:
      command: check advisories
  - name: Check license and source bans - bans licenses sources
    uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
    with:
      command: check bans licenses sources

