name: Check Rust Licenses
description: Check Rust licenses and source bans

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: 'false'
  - name: Check license and source bans - advisories
    continue-on-error: true
    uses: EmbarkStudios/cargo-deny-action@76cd80eb775d7bbbd2d80292136d74d39e1b4918 # v2.0.14
    with:
      command: check advisories
  - name: Check license and source bans - bans licenses sources
    uses: EmbarkStudios/cargo-deny-action@76cd80eb775d7bbbd2d80292136d74d39e1b4918 # v2.0.14
    with:
      command: check bans licenses sources

