name: Check Rust Licenses
description: Check Rust licenses and source bans

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: 'false'
  - name: Check license and source bans - advisories
    continue-on-error: true
    uses: EmbarkStudios/cargo-deny-action@30f817c6f72275c6d54dc744fbca09ebc958599f # v2.0.12
    with:
      command: check advisories
  - name: Check license and source bans - bans licenses sources
    uses: EmbarkStudios/cargo-deny-action@30f817c6f72275c6d54dc744fbca09ebc958599f # v2.0.12
    with:
      command: check bans licenses sources

