name: Run Rust Package Sec Audit
description: |
  Check for vulnerable dependencies in Rust packages.

  Run with mobilecoin/rust-base image.

  Requires checks:write and issues:write permissions.

inputs:
  github_token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: false

  - name: run cargo audit
    uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
