name: Run git-town
description: |
  Requires contents:read and pull-requests:write permissions.

inputs:
  main-branch:
    description: The main branch to use for git-town commands
    default: main

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: 'false'
  - name: Run git-town
    uses: git-town/action@fea06c3ad469d1bc360b6453c5290efdf9b4db21 # v1.3.0
    with:
      main-branch: ${{ inputs.main-branch }}
