name: Mobilecoin Enclave Measurements
description: Output the the MRSIGNER/MRENCLAVE Hex values. Requires using the mobilecoin/rust-sgx-base image you built with.

inputs:
  enclave_so_path:
    description: path to the enclave singed.so file

outputs:
  mrsigner:
    value: ${{ steps.measurement.outputs.mrsigner }}
    description: Hex value of MRSIGNER measurement
  mrenclave:
    value: ${{ steps.measurement.outputs.mrenclave }}
    description: Hex value of MRENCLAVE measurement

runs:
  using: composite
  steps:
  - name: Get MRSIGNER/MRENCLAVE hash values
    id: measurement
    shell: bash
    run: |
      # Get MRSIGNER/MRENCLAVE values
      dump=$(sgx_sign dump -enclave "${{ inputs.enclave_so_path }}" -dumpfile /dev/stdout 2>&1)
      # Get MRSIGNER value from the enclave signed.so file
      mrsigner=$(echo "${dump}" | grep -A 2 -m 1 "mrsigner->value" | grep -v "mrsigner->value" | sed -r 's/(0x|\s+)//g' | tr -d "\n")

      # Get MRENCLAVE value from the enclave signed.so file
      mrenclave=$(echo "${dump}" | grep -A 2 -m 1 "enclave_hash.m" | grep -v "enclave_hash.m" | sed -r 's/(0x|\s+)//g' | tr -d "\n")

      echo "MRSIGNER: ${mrsigner}"
      echo "MRENCLAVE: ${mrenclave}"
      echo "mrsigner=${mrsigner}" >> ${GITHUB_OUTPUT}
      echo "mrenclave=${mrenclave}" >> ${GITHUB_OUTPUT}
