name: Setup Rust Problem Matchers
description: Set up github problem matchers for Rust

runs:
  using: composite
  steps:
  - name: setup problem matchers
    uses: r7kamura/rust-problem-matchers@7e46a19e8d2f3a44f97b551aee14a7b3cc18fcd0 # v1.5.1

