name: Lint Helm
description: run helm lint

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: false

  - name: Lint Helm
    uses: mobilecoinofficial/gha-k8s-toolbox@b080a4e3a92ff791b27c15d09563b163d3582553
    with:
      action: helm-lint
