name: Lint Helm
description: run helm lint

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0

  - name: Lint Helm
    uses: mobilecoinofficial/gha-k8s-toolbox@d7a8fa9873d05eb1f4874fbfe2ee3e85552bc36d
    with:
      action: helm-lint
