name: Lint Docker
description: Lint dockerfiles with hadolint and reviewdog

inputs:
  submodules:
    description: true. false or recursive
    required: false
    default: 'false'

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: ${{ inputs.submodules }}

  - name: Install wget
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y wget

  - name: Run hadolint with reviewdog
    uses: reviewdog/action-hadolint@fc7ee4a9f71e521bc43e370819247b70e5327540 # v1.50.2
    with:
      level: error
      reporter: github-pr-review
      exclude: |
        *.dockerignore
