name: Lint Shell Scripts
description: run shellcheck with reviewdog

inputs:
  submodules:
    description: true. false or recursive
    required: false
    default: 'false'

runs:
  using: composite
  steps:
  - name: Checkout
    uses: mobilecoinofficial/gh-actions/checkout@v0
    with:
      submodules: ${{ inputs.submodules }}

  - name: Install xz-utils
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y xz-utils

  - name: Run shellcheck with reviewdog
    uses: reviewdog/action-shellcheck@1bb9751763fdfbee4b5043772c37374f103bff9e # v1.31.0
    with:
      level: error
      reporter: github-pr-review
