name: Mobilecoin Go Binary Cache
description: Standardized golang binary cache setup

inputs:
  cache_buster:
    description: "string to make cache unique"
    required: false
  path:
    description: "path to mount cache"
    required: false
    default: |
      cache
  additional_keys:
    description: "additional values to add to the cache key"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "did we get a cache hit?"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
  - name: Cache build binaries
    id: cache
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: ${{ inputs.path }}
      # Key is a hash of all the .go, .p files.
      # if code changes, invalidate cache and rebuild
      key: ${{ inputs.cache_buster }}${{ inputs.additional_keys }}-${{ runner.os }}-${{ hashFiles('**/*.go', 'go.mod', 'go.sum') }}-go-build-artifacts
