name: Mobilecoin Go Binary Cache
description: Standardized golang binary cache setup

inputs:
  cache_buster:
    description: "string to make cache unique"
    required: false
  path:
    description: "path to mount cache"
    required: false
    default: |
      cache
  additional_keys:
    description: "additional values to add to the cache key"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "did we get a cache hit?"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
  - name: Install zstd if needed
    uses: mobilecoinofficial/gh-actions/install-zstd@v0

  - name: Create cache directory
    shell: bash
    run: mkdir -p ${{ inputs.path }}

  - name: Cache build binaries
    id: cache
    uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
    with:
      path: ${{ inputs.path }}
      # Key is a hash of all the .go, .p files.
      # if code changes, invalidate cache and rebuild
      key: ${{ inputs.cache_buster }}${{ inputs.additional_keys }}-${{ runner.os }}-${{ hashFiles('**/*.go', 'go.mod', 'go.sum') }}-go-build-artifacts
