name: Mobilecoin Checkout
description: Check out and set the git safe dir to include the github workspace

inputs:
  token:
    description: GitHub actions token
    required: false
    default: ${{ github.token }}
  path:
    description: Path under workspace to clone repo to.
    required: false
    default: ''
  repository:
    description: Repository name with owner if not current.
    required: false
    default: ${{ github.repository }}
  ref:
    description: The branch, tag or SHA to checkout, if not current.
    required: false
    default: ''
  submodules:
    description: true. false or recursive
    required: false
    default: 'true'
  lfs:
    description: true or false
    required: false
    default: 'false'

outputs: {}

runs:
  using: composite
  steps:
  - name: Install git if required
    uses: mobilecoinofficial/gh-actions/install-git@v0

  - name: Checkout
    uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    with:
      submodules: ${{ inputs.submodules }}
      token: ${{ inputs.token }}
      path: ${{ inputs.path }}
      ref: ${{ inputs.ref }}
      lfs: ${{ inputs.lfs }}
      repository: ${{ inputs.repository }}
      # set-safe-directory: true <- not sure what the point is since this doesn't persist beyond the "Checkout" step

  - name: Set Git Safe Directory
    shell: bash
    run: |
      git config --global --add safe.directory "$(pwd)"
