name: Mobilecoin Checkout
description: Check out and set the git safe dir to include the github workspace

inputs:
  token:
    description: GitHub actions token
    required: false
    default: ${{ github.token }}

outputs: {}

runs:
  using: composite
  steps:
  - name: Install git if required
    uses: mobilecoinofficial/gh-actions/install-git@dba9380a9dbf47d0d6a0e95c2f7b5ffb21d08d56

  - name: Checkout
    uses: actions/checkout@v4
    with:
      submodules: recursive
      token: ${{ inputs.token }}

  - name: Set Git Safe Directory
    shell: bash
    run: |
      git config --global --add safe.directory "$(pwd)"
      git config --global -l --show-origin
