name: Mobilecoin Checkout
description: Check out and set the git safe dir to include the github workspace

inputs: {}

outputs: {}

runs:
  using: composite
  steps:
  - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
  - name: Set Git Safe Directory
    run: |
      git config --global --add safe.directory "${{ github.workspace }}"
