name: Mobilecoin Checkout
description: Check out and set the git safe dir to include the github workspace

inputs:
  safe:
    description: Git "safe-directory" - use github.workspace
    required: true

outputs: {}

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      submodules: recursive
  - name: Set Git Safe Directory
    shell: bash
    run: |
      echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      echo "pwd $(pwd)"
      git config --global --add safe.directory "${{ inputs.safe }}"
      git config --global -l --show-origin
