name: Mobilecoin Checkout
description: Check out and set the git safe dir to include the github workspace

inputs: {}

outputs: {}

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      submodules: recursive
  - name: Set Git Safe Directory
    shell: bash
    run: |
      git config --global --add safe.directory "$(pwd)"
      git config --global -l --show-origin
