name: GH Release Downloader
description: Wrapper for robinraju/release-downloader

inputs:
  repository:
    description: 'The source repository path. Expected format {owner}/{repo}'
    default: ${{ github.repository }}
    required: false
  latest:
    description:
      'A flag to choose between latest release and remaining releases'
    default: 'false'
    required: false
  preRelease:
    description:
      'A flag to download from prerelease. It should be combined with latest flag'
    default: 'false'
    required: false
  tag:
    description: 'The github tag to download the release from'
    default: ''
    required: false
  fileName:
    description:
      "Name of the file to download (use '*' to download all assets other than tarball or zipball)"
    default: ''
    required: false
  tarBall:
    description: 'Download tarball from assets'
    default: 'false'
    required: false
  zipBall:
    description: 'Download zipball from assets'
    default: 'false'
    required: false
  out-file-path:
    description:
      'Relative path under $GITHUB_WORKSPACE to place the downloaded files'
    default: '.'
    required: true
  extract:
    description:
      'If the downloaded assets should be extracted to `out-file-path`. Supports tar, tar.gz and zip'
    default: 'false'
    required: false
  token:
    description: 'Github token to access private repos'
    default: ${{ github.token }}
    required: false
  github-api-url:
    description:
      'The URL of the Github API, only use this input if you are using Github Enterprise'
    default: 'https://api.github.com'
    required: false
  releaseId:
    description: 'The release id to download the file from'
    default: ''
    required: false

outputs:
  tag_name:
    value: ${{ steps.release-downloader.outputs.tag_name }}
    description: 'The github tag used to download the release'
  release_name:
    value: ${{ steps.release-downloader.outputs.release_name }}
    description: 'The release name / title'
  downloaded_files:
    value: ${{ steps.release-downloader.outputs.downloaded_files }}
    description:
      "The array of downloaded files, useful when using wildcard '*' to download multiple files."

runs:
  using: composite
  steps:
  - name: Release Downloader
    uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
    with:
      repository: ${{ inputs.repository }}
      latest: ${{ inputs.latest }}
      preRelease: ${{ inputs.preRelease }}
      tag: ${{ inputs.tag }}
      fileName: ${{ inputs.fileName }}
      tarBall: ${{ inputs.tarBall }}
      zipBall: ${{ inputs.zipBall }}
      out-file-path: ${{ inputs.out-file-path }}
      extract: ${{ inputs.extract }}
      token: ${{ inputs.token }}
      github-api-url: ${{ inputs.github-api-url }}
      releaseId: ${{ inputs.releaseId }}
