# Copyright (c) 2022 MobileCoin Inc.
name: tag

on:
  push:
    branches:
    - main
  # Refresh images on the first of every month for OS security updates.
  # schedule:
  # - cron: '0 0 1 * *'

jobs:
  tag:
    runs-on: ubuntu-24.04
    steps:
    # We need to use an external PAT here because GHA will not run downstream events if we use the built in token.
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}

    - name: Bump GitHub tag
      id: bump
      uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # 1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        WITH_V: 'true'
        DEFAULT_BUMP: patch
        DRY_RUN: 'true'

    # Doing manual tags because anothrNick/github-tag-action won't retag a commit.
    - name: Get major and minor values for new tag
      id: tags
      env:
        TAG: ${{ steps.bump.outputs.new_tag }}
      run: |
        export MAJOR_MINOR=${TAG%.*}
        export MAJOR=${MAJOR_MINOR%.*}
        git tag --force "${MAJOR}"
        git tag --force "${MAJOR_MINOR}"
        git tag --force "${TAG}"
        git push --tags --force
